name: gh-pages
on: [workflow_dispatch]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pdm-project/setup-pdm@v4
      - name: Install dependencies
        run: |
          pdm install --dev
      - name: Sphinx build
        run: |
          pdm run docs
      - name: Upload artifact 
        uses: actions/upload-artifact@v4
        with:
          name: embr-docs
          path: docs/_build

  publish-docs:
    needs: build-docs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: embr-docs
          path: pages/
      - name: Disable Jekyll
        run: |
          touch pages/.nojekyll
      - name: Publish documentation
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: pages/
          clean: false

